"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { getGallery, getImageUrl, getStyles } from "@/lib/api";
import { Image as ImageIcon, RefreshCw, Clock, Sparkles } from "lucide-react";
import type { GalleryImage } from "@/types/style";

interface RecentGalleryProps {
  refreshTrigger: number;
}

export default function RecentGallery({ refreshTrigger }: RecentGalleryProps) {
  const [items, setItems] = useState<GalleryImage[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [styleMap, setStyleMap] = useState<Record<string, string>>({});
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);

  useEffect(() => {
    const initialize = async () => {
      try {
        setError("");

        // Load styles map dynamically
        const stylesResponse = await getStyles({ limit: 100 });
        const mapping: Record<string, string> = {};
        stylesResponse.items.forEach((style) => {
          mapping[style.id] = style.title;
        });
        setStyleMap(mapping);

        // Load recent generated images
        const galleryResponse = await getGallery(1);
        setItems(galleryResponse.items as GalleryImage[] || []);
      } catch (err) {
        console.error("Failed to load recent gallery:", err);
        setError("Could not retrieve recently generated images.");
      } finally {
        setLoading(false);
      }
    };

    initialize();
  }, [refreshTrigger]);

  const handleRefresh = async () => {
    try {
      setLoading(true);
      const galleryResponse = await getGallery(1);
      setItems(galleryResponse.items as GalleryImage[] || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return "";
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString(undefined, {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      });
    } catch {
      return "";
    }
  };

  return (
    <section id="gallery" className="space-y-8 scroll-mt-24">
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 border-b border-white/5 pb-6">
        <div>
          <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight text-white font-outfit flex items-center gap-2.5">
            <Sparkles className="text-indigo-400 h-7 w-7" />
            Recently Generated Art
          </h2>
          <p className="mt-2 text-sm text-gray-400">
            Browse creative masterpieces generated by other artists and yourself.
          </p>
        </div>

        <button
          onClick={handleRefresh}
          disabled={loading}
          className="self-start sm:self-auto inline-flex items-center gap-2 rounded-xl bg-white/5 border border-white/10 px-4 py-2.5 text-xs font-bold text-gray-300 hover:bg-white/10 hover:text-white hover:border-white/20 active:scale-95 transition-all cursor-pointer disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </div>

      {loading && items.length === 0 ? (
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          {Array.from({ length: 4 }).map((_, index) => (
            <div
              key={index}
              className="aspect-square animate-pulse rounded-2xl bg-white/5"
            />
          ))}
        </div>
      ) : error ? (
        <div className="rounded-2xl border border-red-500/20 bg-red-950/20 p-8 text-center text-red-400">
          {error}
        </div>
      ) : items.length === 0 ? (
        <div className="rounded-3xl border border-dashed border-white/10 bg-white/5 p-16 text-center space-y-4 max-w-lg mx-auto">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-indigo-500/10 text-indigo-400">
            <ImageIcon size={30} />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white font-outfit">No artwork generated yet</h3>
            <p className="mt-1 text-sm text-gray-400 font-light">
              Be the first to upload an image and transform it into a stunning AI art piece!
            </p>
          </div>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          <AnimatePresence>
            {items.map((item, index) => {
              // style_id may be present; fall back to "AI Generated"
              const styleTitle = item.style_id
                ? (styleMap[item.style_id] || item.style_id)
                : "AI Generated";
              const generatedSrc = getImageUrl(item.image_url);
              const originalSrc = getImageUrl(item.original_url || "");

              return (
                <motion.div
                  key={item.task_id ?? index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.05 }}
                  className="group relative overflow-hidden rounded-2xl border border-white/5 bg-white/5 shadow-lg hover:border-white/10 transition-all duration-300"
                  onMouseEnter={() => setHoveredIndex(index)}
                  onMouseLeave={() => setHoveredIndex(null)}
                >
                  <div className="relative aspect-square overflow-hidden bg-white/5">
                    {/* Generated Image (default) */}
                    <img
                      src={generatedSrc}
                      alt="AI generated image"
                      draggable={false}
                      className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"
                    />

                    {/* Original Image (fades in on hover) */}
                    {hoveredIndex === index && originalSrc && (
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="absolute inset-0 z-10"
                      >
                        <img
                          src={originalSrc}
                          alt="Original image"
                          draggable={false}
                          className="h-full w-full object-cover"
                        />
                        <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
                          <span className="bg-black/70 text-white text-[10px] font-bold tracking-wider uppercase border border-white/10 px-3 py-1.5 rounded-full backdrop-blur-md">
                            Original Photo
                          </span>
                        </div>
                      </motion.div>
                    )}

                    {/* Style badge */}
                    <div className="absolute left-3 top-3 z-20 flex flex-col gap-1.5">
                      <span className="rounded-full bg-black/60 border border-white/10 px-2.5 py-1 text-[10px] font-bold text-indigo-300 uppercase tracking-wider shadow-sm backdrop-blur-md">
                        {styleTitle}
                      </span>
                    </div>

                    {/* Compare hint */}
                    {hoveredIndex !== index && (
                      <div className="absolute bottom-3 right-3 z-20 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                        <span className="bg-black/60 border border-white/10 text-[10px] font-medium px-2.5 py-1 rounded-full backdrop-blur-md text-gray-300">
                          Hover to compare
                        </span>
                      </div>
                    )}
                  </div>

                  {/* Card Info — NO prompt text shown */}
                  <div className="p-4 space-y-1.5 bg-[#080812]">
                    <p className="text-[10px] text-gray-500 font-bold tracking-wide flex items-center gap-1 font-mono uppercase">
                      <Clock size={11} className="text-gray-600" />
                      {formatDate(item.created_at)}
                    </p>
                    <p className="text-sm font-semibold text-gray-300 line-clamp-1 leading-snug group-hover:text-white transition-colors">
                      {styleTitle}
                    </p>
                  </div>
                </motion.div>
              );
            })}
          </AnimatePresence>
        </div>
      )}
    </section>
  );
}
